# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            NEAT
tagline:          'no effort automated transporter'
description:      ''
url:              https://proj.neatrobot.site/
baseurl:          /


paginate:         5

# Custom vars
version:          2.1.0

